[build]
  Command = "yarn build:lambda"
  Functions = "lambda"
[context.production]
  Command = "npm run schema:start-and-publish && npm run build && npm run build:lambda"
[context.deploy-preview]
  Command = "npm run schema:start-and-check && npm run build && npm run build:lambda"
